apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-stable
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
